version: 2.1

defaults: &defaults
  macos:
    xcode: "15.3.0"

bundle_install: &bundle_install
  run:
    name: bundle install
    command: |
      bundle install --path .bundle

copy_test_results_to_artifacts: &copy_test_results_to_artifacts
  run:
    name: Copy test results to artifacts folder
    command: |
      mkdir /tmp/test-results
      cd /tmp/test-results
      mv $(find ~/project -name "*.xcresult") .
      tar -cvzf test-results.tar.gz *.xcresult
    when: on_fail

store_test_artifacts: &store_test_artifacts
  store_artifacts:
    path: /tmp/test-results/test-results.tar.gz
    destination: test-results.tar.gz
    when: on_fail

jobs:
  run-ui-tests:
    <<: *defaults
    steps:
      - run:
          name: Attach null audio driver
          command: |
            git clone --depth 1 https://github.com/russellporter/NullAudioDriver.git
            
            ./NullAudioDriver/install.sh
            sudo rm -rf NullAudioDriver
      - checkout
      - *bundle_install
      - run:
          name: Run UI Tests
          command: |
            bundle exec fastlane run_ui_tests
      - *copy_test_results_to_artifacts
      - *store_test_artifacts

workflows:
  version: 2.1

  Run UI tests:
    jobs:
      - run-ui-tests
